[package]
name = "tls_validator"
version.workspace = true
edition.workspace = true

[dependencies]
rustls = { git = "https://github.com/ethan-vanderheijden/rustls" }
capsule.workspace = true
common = { path = "../common"}
webpki-roots = "1.0.0"
tracing = "0.1"
colored = "3.0"
anyhow = "1.0"
