app_name = "tap_tunnel"
main_core = 0
worker_cores = []

[mempool]
    capacity = 65535
    cache_size = 256

[[ports]]
    name = "cap0"
    device = "net_tap0"
    args = "mac=fixed"
    rx_cores = [0]
    tx_cores = [0]

[[ports]]
    name = "cap1"
    device = "net_tap1"
    args = "mac=fixed"
    rx_cores = [0]
    tx_cores = [0]
