[package]
name = "tunnel"
version.workspace = true
edition.workspace = true

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
capsule.workspace = true
signal-hook = "0.3"
tls_validator = { path = "../../tls_validator" }
common = { path = "../../common" }
anyhow = "1.0"
