app_name = "tunnel"
main_core = 0
worker_cores = []

[mempool]
    capacity = 65535
    cache_size = 256

[[ports]]
    name = "inside"
    device = "net_tap0"
    args = "mac=fixed,iface=inside"
    rx_cores = [0]
    tx_cores = [0]

[[ports]]
    name = "outside"
    device = "net_tap1"
    args = "mac=fixed,iface=outside"
    rx_cores = [0]
    tx_cores = [0]
